language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Kbt6oAUMuUuMDLh7vxA8aSG1DE4hIqQf/1AFEdTzwtluxjvVXWdMFcif2sdNyBlsii3T2oyRMHhh6EOaAjP0hsp696DNPrheVp/auM56OsBPAz2m5S+70XqKYj+vMzV9tFhH1VopZadfUeYnf4AzJKd72PWGLOABo5xiw9mczX9bTvt7U50oyrRxaXsbUT/nfxpjrCjGhX8TroxUCaRzqrBIqYCxSgn151CWykbaaAcT8bNxqJLpZHbuN4Qg607P8UQ2eouUJGd8+6XDmV9RPmvsYLxa5tZ+Xe2r3QPScoSkCJV5VzKYzJX6xPn6O+pb457e1M8uvYOgWKGQgk29/pqNxpW5OTXnL0ENCfMpkwxM18f3bXIN7xc8ureKVYKWJ30XrnyLLMu7D3qoq5+g4LmbCugZmFthJfbOoOpQu7i2MvlF3LjRlvU1IrYdBJJMBjzD0ygzmDAXXC2/qCL6CdGq8b7yYlTkzBof4V1zcHNV7d68BLlSQVaxqjZn0MAtasx/7IFHQ9oAbjDQ/MET6f8kt2EgR09dabqvW6q+IbZeQI8+3MOyJHwov//70SKfTB25Ycm+/p03ml/2y+7FK/QqFoLZwbS+LFwkvOx0V4WT4yc9dJ2dXqosxhG1mxqanWb8+mh6gYn+5jdBkYB3vPT/NVEb01msy5LJUb4PGT4=
  app: addressbook-jwh
  on:
    repo: HarrisJW/addressbook
    branch: todo_tasks
