language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: CMqtehSQsIgEo4SgDOCO2VFIbzVQfc3+1GO4l2r31iutBSY6JqoBS2I7MhAE2B6l48/kOGxW0DZLlWlD/0yDIs6AdSgFQtV80yEy7YlZDiN9ZCaKk0JZLepyxUDJ9fhek+4vULs4j01BFdAc9fQQEExp7HMNOfMXZCgofPP5JgbjbV8D5sLOxlhtaDpFSr/a5Kk1WHi+z5xEINT1QLxvO2b3RyAn3uGPWyRgwgpOxvt9SHrSLEPOlZ7zOFnLrfZd/QDipM0SY7UevK7o3DvJmg/kxD0+XchwMLyf6sZ+dQIfZNqu6nwwPpH8T5JOuhcoW32vkTLOapygiFmbWfLNHx5li8jy+718jugutOpSGXXpbKhA31p15DANKtauqedwVuw0y+JBkEyQbputqeBUtgVDNrGq4pww7eg0SDekiaHDW+IGZ66bvogfoYbC/pNpDqyny+SFVc5mgOsdrD9KAPTztl0r7NJu8ny0MQhE0WJ97SWUuqcFhDnEpvzQwFtwYLg0DiJvxELXn3V3ua3bvy+o2mqW88/MjQu4ml/oudQh9/TVmeNF/DR3u1hGPZAZPPtpcEILPYtC1jpFGD18AeemUpEtr+PyUgmQyUdpvziGtwYo7v587uro08sq1Nye53EuRv9Lph4p38iCvAESfeteqFwBDTDe6G2WB/LZKL0=
  app: harrisjw-addressbook
  on:
    repo: HarrisJW/addressbook
    branch: todo_tasks
