language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Er3XcXEb+DfcChWg1EtS40GGwjZ66JxLVFaGOkAWAwHrvqsZ7DfHJqywKFaK2lA1ehCqomZrAYqKmQ9Sd4KCo4MbF4co7x22V1rniloFw8Ay/F9s46Y6aXPY7BeOPdKFtQyQIYc/ZFl21LIY/au68KR0mPFzKz7px/Pab/YDtfoNU4xj2D+2QhVzifQH6S9xK0VKMGAbJhQ9l+hyrP4E2Fr5//Bp9huIEUKZWE9okPQ8+46xaohi96zMqP2yxqs17SR5h9/NsZdp50B5UnGT9zU39Oy8T/sYZLzDY9oyN+xSAJuXnzSoXChZw5GjFZ9RrjfRJRxRVtl2WVJX3ty3EEfNhSPSMtfQ3u0onTrWdTqhE89zTnMmkLj7A7Tni89iNJ/l38PXTmLJKQ0tBrQ1YI21cH8fygi+P9hSAYGAi5WHtkeTIERjHhTjAaevhpJdAbAvWZ/JSUAwUYAYOi69/HSps0W6F+drOs7GW0W/kHjFvpxOjhoSPH2W1nT4t/jI+mWP0yfPC/fYC3odIX9KF4obzYwWIspRMwkacjGrLBwtq7Ak36NXzGN2Y6krqiFuJxVz8o3bnmqHWn3MPijaeJTZBscCVghaABhTgPrak1aQzjr9HXhpc7l9TYSnBRRu0PoSK9sy4zTHtrAEdvis53EWzExFakrxMm9+dOPf/T8=
  app: addressbook-jwh
  on:
    repo: HarrisJW/addressbook
    branch: master
