language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: NpIu281EEgJN3gtA/B49rcXFjh1HrWiIviE+UjbFmlDS8fVWLcq8QShwSg6FvLTirdkxEQPkK21XrpBMSJHT7ETARX5912UleBvRaR/bZP+mWq9+jPQA5v3hpTn72pRV68lOPDXqAGS4EnGdAvC0oJU3tzOC63bW7EjbPJvTSXOvRemCMnBmbNpPeqsqS8sNptuV6jlVMKnZLrAAb7jEcA+RDqb1flclCw8WCGG76cKRxyVqaNgtLQPur6MkrphU4iX5JfS78hRH7QgNyBcDYZvJoj4389d9RyX5oUpUHViIfHdzwKM7GlTbSnR3NNA/azJ52pLSVFInYn1sc460h3YhcWX6fRT83mXcw5Tbquqi/lhBUkwD29XyNxZfwm5/jRn2ZH1NODRswMHZcwg7PbJBAiD1zHZuAN0amONDYApOBtqHPP6H8bRTZ5fPhb/qxyCfzd410EDEK63oVFCq/c5lUIaDJ65qzCVe5y5iA3BYu8XM37eZUoVyaHTYt6qGY8CiiVeDgbd5vucrGJ1HFq85/8Z7ieOF5bXUFtxxXklIUKON3WMsnu43Z+AtZPtilOeOJA0yxMheZwNA5C/kFAh3un4V6pePya5u7tchvDY41vePezyJPveyC5OmgGrgLFSU6He22QSz3YKBEwBAc8x19tPy1Io2xTQ/e2O/whg=
  app: HarrisJW-addressbook
  on:
    repo: HarrisJW/addressbook
    branch: todo_tasks
